services:
  sonic:
    image: sonic:latest
    container_name: sonic
    hostname: sonic
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml
      - ./key:/app/key
    restart: always
    ports:
      - "127.0.0.1:18545:18545"
      - "0.0.0.0:5050:5050"
    environment:
      - SONIC_VALIDATOR_ID=${SONIC_VALIDATOR_ID}
      - SONIC_PUBKEY=${SONIC_PUBKEY}
      - SONIC_NAT=${SONIC_NAT}
      - SONIC_BOOT_NODES=${SONIC_BOOT_NODES}
